# Copyright (c) 2018 Bitwise IO, Inc.
# Licensed under Creative Commons Attribution 4.0 International License
# https://creativecommons.org/licenses/by/4.0/

FROM jekyll/builder:3.5

COPY Gemfile .
COPY _config.yml .