name: Deploy-to-grid.splinter.dev

on:
  workflow_dispatch:

concurrency:
  group: "${{ github.ref }}-${{ github.workflow }}"
  cancel-in-progress: true

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
  AWS_ROLE_ARN: ${{ vars.AWS_ROLE_ARN }}
  JEKYLL_ENV: 'production'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.3'
          bundler-cache: true
      - name: Install Just
        run: sudo snap install --edge --classic just
      - name: Build
        run: just build
      - name: "Deploy to AWS S3"
        shell: bash
        run: |
          export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s" \
          $(aws sts assume-role \
                --role-arn ${{ vars.AWS_ROLE_ARN }} \
                --role-session-name GithubActions \
                --query "Credentials.[AccessKeyId,SecretAccessKey,SessionToken]" \
                --output text))
          aws s3 sync ./_site/ s3://${{ vars.AWS_S3_BUCKET_NAME }} \
              --delete --cache-control max-age=604800
          aws cloudfront create-invalidation \
              --distribution-id ${{ vars.AWS_CLOUDFRONT_DISTRIBUTION_ID }} \
              --paths "/*"
